POST /api/2.3/tenders?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2253
Content-Type: application/json
Host: api-sandbox.mepps.openprocurement.net

{
  "data": {
    "procurementMethod": "limited", 
    "status": "active", 
    "title": "Articole de papetărie şi alte articole din hârtie", 
    "procurementMethodType": "reporting", 
    "title_en": "Stationery and paper", 
    "description_en": "Stationery and paper", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://www.edu.gov.md/", 
        "email": "svetlana.lucinscaia@edu.md", 
        "telephone": "212701", 
        "name": "Lucinscaia Svetlana"
      }, 
      "identifier": {
        "scheme": "MD-IDNO", 
        "id": "1003254747454", 
        "legalName": "Ministerul Educatiei al Republicii Moldova"
      }, 
      "name": "Ministerul Educatiei al Republicii Moldova", 
      "address": {
        "postalCode": "MD-2033", 
        "countryName": "Republica Moldova", 
        "streetAddress": "Piața Marii Adunari Naționale, 1", 
        "region": "Chisinau", 
        "locality": "Chisinau"
      }
    }, 
    "title_ru": "Канцелярские товары и бумага", 
    "items": [
      {
        "description": "Articole de papetărie şi alte articole din hârtie", 
        "classification": {
          "scheme": "CPV", 
          "description": "Articole de papetărie şi alte articole din hârtie", 
          "id": "30199000-0"
        }, 
        "description_en": "Stationery and paper", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "description": "Послуги шкільних їдалень", 
            "id": "55.51.10.300"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "MD-2033", 
          "countryName": "Republica Moldova", 
          "streetAddress": "Piața Marii Adunari Naționale, 1", 
          "region": "Chisinau", 
          "locality": "Chisinau"
        }, 
        "deliveryDate": {
          "startDate": "2017-12-21T13:26:11.907207", 
          "endDate": "2017-12-24T13:26:11.907207"
        }, 
        "description_ru": "Канцелярские товары и бумага", 
        "id": "2dc54675d6364e2baffbc0f8e74432ac"
      }
    ], 
    "owner": "broker", 
    "value": {
      "currency": "MDL", 
      "amount": 500000, 
      "valueAddedTaxIncluded": false
    }, 
    "description_ru": "Канцелярские товары и бумага"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.mepps.openprocurement.net/api/2.3/tenders/667ddc4fbc794e27955f606e324e989a
{
  "access": {
    "transfer": "72067ab011e242429dede7ecbc133a1f", 
    "token": "1142190ec4f04f50a88fb21c1cd589e4"
  }, 
  "data": {
    "procurementMethod": "limited", 
    "status": "active", 
    "title": "Articole de papetărie şi alte articole din hârtie", 
    "items": [
      {
        "description": "Articole de papetărie şi alte articole din hârtie", 
        "classification": {
          "scheme": "CPV", 
          "description": "Articole de papetărie şi alte articole din hârtie", 
          "id": "30199000-0"
        }, 
        "description_en": "Stationery and paper", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "MD-2033", 
          "countryName": "Republica Moldova", 
          "streetAddress": "Piața Marii Adunari Naționale, 1", 
          "region": "Chisinau", 
          "locality": "Chisinau"
        }, 
        "deliveryDate": {
          "startDate": "2017-12-21T13:26:11.907207+02:00", 
          "endDate": "2017-12-24T13:26:11.907207+02:00"
        }, 
        "description_ru": "Канцелярские товары и бумага", 
        "id": "2dc54675d6364e2baffbc0f8e74432ac"
      }
    ], 
    "title_en": "Stationery and paper", 
    "value": {
      "currency": "MDL", 
      "amount": 500000.0, 
      "valueAddedTaxIncluded": false
    }, 
    "dateModified": "2017-12-19T13:26:13.446048+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://www.edu.gov.md/", 
        "email": "svetlana.lucinscaia@edu.md", 
        "telephone": "212701", 
        "name": "Lucinscaia Svetlana"
      }, 
      "identifier": {
        "scheme": "MD-IDNO", 
        "id": "1003254747454", 
        "legalName": "Ministerul Educatiei al Republicii Moldova"
      }, 
      "name": "Ministerul Educatiei al Republicii Moldova", 
      "address": {
        "postalCode": "MD-2033", 
        "countryName": "Republica Moldova", 
        "streetAddress": "Piața Marii Adunari Naționale, 1", 
        "region": "Chisinau", 
        "locality": "Chisinau"
      }
    }, 
    "date": "2017-12-19T13:26:13.444214+02:00", 
    "procurementMethodType": "reporting", 
    "description_en": "Stationery and paper", 
    "title_ru": "Канцелярские товары и бумага", 
    "owner": "broker", 
    "description_ru": "Канцелярские товары и бумага", 
    "id": "667ddc4fbc794e27955f606e324e989a", 
    "tenderID": "MD-2017-12-19-000001"
  }
}

