POST /api/2.3/tenders?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2253
Content-Type: application/json
Host: api-sandbox.mepps.openprocurement.net

{
  "data": {
    "procurementMethod": "limited", 
    "status": "active", 
    "title": "Articole de papetărie şi alte articole din hârtie", 
    "procurementMethodType": "reporting", 
    "title_en": "Stationery and paper", 
    "description_en": "Stationery and paper", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://www.edu.gov.md/", 
        "email": "svetlana.lucinscaia@edu.md", 
        "telephone": "212701", 
        "name": "Lucinscaia Svetlana"
      }, 
      "identifier": {
        "scheme": "MD-IDNO", 
        "id": "1003254747454", 
        "legalName": "Ministerul Educatiei al Republicii Moldova"
      }, 
      "name": "Ministerul Educatiei al Republicii Moldova", 
      "address": {
        "postalCode": "MD-2033", 
        "countryName": "Republica Moldova", 
        "streetAddress": "Piața Marii Adunari Naționale, 1", 
        "region": "Chisinau", 
        "locality": "Chisinau"
      }
    }, 
    "title_ru": "Канцелярские товары и бумага", 
    "items": [
      {
        "description": "Articole de papetărie şi alte articole din hârtie", 
        "classification": {
          "scheme": "CPV", 
          "description": "Articole de papetărie şi alte articole din hârtie", 
          "id": "30199000-0"
        }, 
        "description_en": "Stationery and paper", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "description": "Послуги шкільних їдалень", 
            "id": "55.51.10.300"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "MD-2033", 
          "countryName": "Republica Moldova", 
          "streetAddress": "Piața Marii Adunari Naționale, 1", 
          "region": "Chisinau", 
          "locality": "Chisinau"
        }, 
        "deliveryDate": {
          "startDate": "2017-12-22T13:36:16.048704", 
          "endDate": "2017-12-25T13:36:16.048704"
        }, 
        "description_ru": "Канцелярские товары и бумага", 
        "id": "2dc54675d6364e2baffbc0f8e74432ac"
      }
    ], 
    "owner": "broker", 
    "value": {
      "currency": "MDL", 
      "amount": 500000, 
      "valueAddedTaxIncluded": false
    }, 
    "description_ru": "Канцелярские товары и бумага"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.mepps.openprocurement.net/api/2.3/tenders/e880178c4afa45b08d1c9873d61cd6eb
{
  "access": {
    "transfer": "10dcd967930c45a5859159cefa780d70", 
    "token": "d4574ebc11b047ae8b360d43132184d3"
  }, 
  "data": {
    "procurementMethod": "limited", 
    "status": "active", 
    "title": "Articole de papetărie şi alte articole din hârtie", 
    "items": [
      {
        "description": "Articole de papetărie şi alte articole din hârtie", 
        "classification": {
          "scheme": "CPV", 
          "description": "Articole de papetărie şi alte articole din hârtie", 
          "id": "30199000-0"
        }, 
        "description_en": "Stationery and paper", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "MD-2033", 
          "countryName": "Republica Moldova", 
          "streetAddress": "Piața Marii Adunari Naționale, 1", 
          "region": "Chisinau", 
          "locality": "Chisinau"
        }, 
        "deliveryDate": {
          "startDate": "2017-12-22T13:36:16.048704+02:00", 
          "endDate": "2017-12-25T13:36:16.048704+02:00"
        }, 
        "description_ru": "Канцелярские товары и бумага", 
        "id": "2dc54675d6364e2baffbc0f8e74432ac"
      }
    ], 
    "title_en": "Stationery and paper", 
    "value": {
      "currency": "MDL", 
      "amount": 500000.0, 
      "valueAddedTaxIncluded": false
    }, 
    "dateModified": "2017-12-20T13:36:17.802034+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://www.edu.gov.md/", 
        "email": "svetlana.lucinscaia@edu.md", 
        "telephone": "212701", 
        "name": "Lucinscaia Svetlana"
      }, 
      "identifier": {
        "scheme": "MD-IDNO", 
        "id": "1003254747454", 
        "legalName": "Ministerul Educatiei al Republicii Moldova"
      }, 
      "name": "Ministerul Educatiei al Republicii Moldova", 
      "address": {
        "postalCode": "MD-2033", 
        "countryName": "Republica Moldova", 
        "streetAddress": "Piața Marii Adunari Naționale, 1", 
        "region": "Chisinau", 
        "locality": "Chisinau"
      }
    }, 
    "date": "2017-12-20T13:36:17.798391+02:00", 
    "procurementMethodType": "reporting", 
    "description_en": "Stationery and paper", 
    "title_ru": "Канцелярские товары и бумага", 
    "owner": "broker", 
    "description_ru": "Канцелярские товары и бумага", 
    "id": "e880178c4afa45b08d1c9873d61cd6eb", 
    "tenderID": "MD-2017-12-20-000001"
  }
}

