PATCH /api/2.3/tenders/667ddc4fbc794e27955f606e324e989a/contracts/117424f98bc04eb5b1f33da4e3c1275e?acc_token=1142190ec4f04f50a88fb21c1cd589e4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 106
Content-Type: application/json
Host: api-sandbox.mepps.openprocurement.net

{
  "data": {
    "period": {
      "startDate": "2017-12-19T13:26:11.907207", 
      "endDate": "2018-12-19T13:26:11.907207"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "Articole de papetărie şi alte articole din hârtie", 
        "classification": {
          "scheme": "CPV", 
          "description": "Articole de papetărie şi alte articole din hârtie", 
          "id": "30199000-0"
        }, 
        "description_en": "Stationery and paper", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "MD-2033", 
          "countryName": "Republica Moldova", 
          "streetAddress": "Piața Marii Adunari Naționale, 1", 
          "region": "Chisinau", 
          "locality": "Chisinau"
        }, 
        "deliveryDate": {
          "startDate": "2017-12-21T13:26:11.907207+02:00", 
          "endDate": "2017-12-24T13:26:11.907207+02:00"
        }, 
        "description_ru": "Канцелярские товары и бумага", 
        "id": "2dc54675d6364e2baffbc0f8e74432ac", 
        "unit": {
          "code": "MON", 
          "name": "month"
        }, 
        "quantity": 9
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "period": {
      "startDate": "2017-12-19T13:26:11.907207+02:00", 
      "endDate": "2018-12-19T13:26:11.907207+02:00"
    }, 
    "dateSigned": "2017-12-19T13:26:11.907207+02:00", 
    "value": {
      "currency": "MDL", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": false
    }, 
    "date": "2017-12-19T13:26:14.214658+02:00", 
    "awardID": "37333e37dfa346608a6d10b38549ceb3", 
    "id": "117424f98bc04eb5b1f33da4e3c1275e", 
    "contractID": "MD-2017-12-19-000001-1"
  }
}

