GET /api/2.3/tenders?opt_pretty=1 HTTP/1.0
Host: api-sandbox.mepps.openprocurement.net

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "next_page": {
    "path": "/api/2.3/tenders?offset=2017-12-20T13%3A36%3A17.802034%2B02%3A00", 
    "uri": "http://api-sandbox.mepps.openprocurement.net/api/2.3/tenders?offset=2017-12-20T13%3A36%3A17.802034%2B02%3A00", 
    "offset": "2017-12-20T13:36:17.802034+02:00"
  }, 
  "data": [
    {
      "id": "e880178c4afa45b08d1c9873d61cd6eb", 
      "dateModified": "2017-12-20T13:36:17.802034+02:00"
    }
  ]
}

