POST /api/2.3/tenders/e880178c4afa45b08d1c9873d61cd6eb/awards?acc_token=d4574ebc11b047ae8b360d43132184d3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 697
Content-Type: application/json
Host: api-sandbox.mepps.openprocurement.net

{
  "data": {
    "date": "2016-01-14T18:07:00.628073+02:00", 
    "status": "pending", 
    "suppliers": [
      {
        "contactPoint": {
          "telephone": "212449", 
          "name": "Vitalie Zlatan", 
          "email": "soleksuk@gmail.com"
        }, 
        "identifier": {
          "scheme": "MD-IDNO", 
          "legalName": "Întreprinderea de stat comunală de catering", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.md/"
        }, 
        "name": "Întreprinderea de stat comunală de catering", 
        "address": {
          "countryName": "Republica Moldova", 
          "postalCode": "MD-2033", 
          "region": "Chisinau", 
          "streetAddress": "Strada Miorita, 33", 
          "locality": "Chisinau"
        }
      }
    ], 
    "id": "d373338bc3324f14b8b3d4af68922773", 
    "value": {
      "currency": "MDL", 
      "amount": 475000, 
      "valueAddedTaxIncluded": "false"
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.mepps.openprocurement.net/api/2.3/tenders/e880178c4afa45b08d1c9873d61cd6eb/awards/89e507f4b41446f29e9ada88300773f5
{
  "data": {
    "status": "pending", 
    "date": "2017-12-20T13:36:18.171434+02:00", 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "212449", 
          "name": "Vitalie Zlatan"
        }, 
        "identifier": {
          "scheme": "MD-IDNO", 
          "legalName": "Întreprinderea de stat comunală de catering", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.md/"
        }, 
        "name": "Întreprinderea de stat comunală de catering", 
        "address": {
          "postalCode": "MD-2033", 
          "countryName": "Republica Moldova", 
          "streetAddress": "Strada Miorita, 33", 
          "region": "Chisinau", 
          "locality": "Chisinau"
        }
      }
    ], 
    "id": "89e507f4b41446f29e9ada88300773f5", 
    "value": {
      "currency": "MDL", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": false
    }
  }
}

