PATCH /api/2.3/tenders/667ddc4fbc794e27955f606e324e989a/cancellations/73cd7880549642ae94fd1c962d241de7?acc_token=1142190ec4f04f50a88fb21c1cd589e4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.mepps.openprocurement.net

{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2017-12-19T13:26:14.585410+02:00", 
    "cancellationOf": "tender", 
    "id": "73cd7880549642ae94fd1c962d241de7"
  }
}

