PUT /api/2.3/tenders/667ddc4fbc794e27955f606e324e989a/documents/20d367ff6fdb48c19976a4ef7a6eb553?acc_token=1142190ec4f04f50a88fb21c1cd589e4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 189
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy253320049977$
Host: api-sandbox.mepps.openprocurement.net

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "title": "Notice-2.pdf", 
    "url": "http://api-sandbox.mepps.openprocurement.net/api/2.3/tenders/667ddc4fbc794e27955f606e324e989a/documents/20d367ff6fdb48c19976a4ef7a6eb553?download=aebda18a63f146d392eca164b682d70b", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-12-19T13:26:13.730272+02:00", 
    "id": "20d367ff6fdb48c19976a4ef7a6eb553", 
    "dateModified": "2017-12-19T13:26:13.766100+02:00"
  }
}

