POST /api/2.3/tenders/e880178c4afa45b08d1c9873d61cd6eb/documents?acc_token=d4574ebc11b047ae8b360d43132184d3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy754052861794$
Host: api-sandbox.mepps.openprocurement.net

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.mepps.openprocurement.net/api/2.3/tenders/e880178c4afa45b08d1c9873d61cd6eb/documents/38438cdd1fba43c69b6882000c9a1a78
{
  "data": {
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.mepps.openprocurement.net/api/2.3/tenders/e880178c4afa45b08d1c9873d61cd6eb/documents/38438cdd1fba43c69b6882000c9a1a78?download=bad2509ea44241749896821dc1c7fb9b", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-12-20T13:36:18.104622+02:00", 
    "id": "38438cdd1fba43c69b6882000c9a1a78", 
    "dateModified": "2017-12-20T13:36:18.104645+02:00"
  }
}

