POST /api/2.3/tenders/667ddc4fbc794e27955f606e324e989a/documents?acc_token=1142190ec4f04f50a88fb21c1cd589e4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy612081653924$
Host: api-sandbox.mepps.openprocurement.net

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.mepps.openprocurement.net/api/2.3/tenders/667ddc4fbc794e27955f606e324e989a/documents/20d367ff6fdb48c19976a4ef7a6eb553
{
  "data": {
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.mepps.openprocurement.net/api/2.3/tenders/667ddc4fbc794e27955f606e324e989a/documents/20d367ff6fdb48c19976a4ef7a6eb553?download=a0b0cb19409746ccbf0051b69cf9747f", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-12-19T13:26:13.730272+02:00", 
    "id": "20d367ff6fdb48c19976a4ef7a6eb553", 
    "dateModified": "2017-12-19T13:26:13.730295+02:00"
  }
}

